kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet restore
      - dotnet build --configuration Release
      - dotnet test --configuration Release --no-build

  # SonarQube 
  - name: sonarqube_begin
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - SonarScanner.MSBuild.exe begin /k:"easv-devops_CalculatorApp_AY4IVCA9EVvRW2O60ES7" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.login=${SONAR_TOKEN}

  - name: rebuild_and_sonarqube_end
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - MsBuild.exe /t:Rebuild
      - SonarScanner.MSBuild.exe end /d:sonar.login=${SONAR_TOKEN}
