kind: pipeline
type: docker
name: dotnet-sonarqube-analysis

steps:
  - name: restore-and-build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet restore
      - dotnet build --configuration Release

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

  - name: sonarqube-analysis
    image: boulundeasv/dotnet-sdk-with-java:latest
    commands:
      - dotnet tool install --global dotnet-sonarscanner
      - export PATH="$PATH:/root/.dotnet/tools"
      - dotnet sonarscanner begin /k:"easv-devops_CalculatorApp_AY4IVCA9EVvRW2O60ES7" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.login="sqp_e3f74eb9afbc43b08266f8489417813c52bbda82"
      - dotnet build --configuration Release
      - dotnet sonarscanner end /d:sonar.login="sqp_e3f74eb9afbc43b08266f8489417813c52bbda82"
