kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet restore
      - dotnet build --configuration Release
      - dotnet test --configuration Release --no-build

  - name: sonarqube_scan
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - sonarscanner begin /k:"easv-devops_CalculatorApp_AY4IVCA9EVvRW2O60ES7" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.login="sqp_e3f74eb9afbc43b08266f8489417813c52bbda82"
      - dotnet build --configuration Release
      - sonarscanner end /d:sonar.login="sqp_e3f74eb9afbc43b08266f8489417813c52bbda82"
