kind: pipeline
type: docker
name: default

steps:
  - name: build-and-test
    image: boulundeasv/dotnet-sdk-with-java 
    commands:
      - dotnet restore
      - dotnet build --configuration Release
      - dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
      - dotnet tool install --global dotnet-reportgenerator-globaltool
      - /root/.dotnet/tools/reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html

  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - /root/.dotnet/tools/reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html
      - sonarscanner begin /k:"easv-devops_CalculatorApp_AY4IVCA9EVvRW2O60ES7" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.login="sqp_e3f74eb9afbc43b08266f8489417813c52bbda82"
      - dotnet build --configuration Release
      - sonarscanner end /d:sonar.login="sqp_e3f74eb9afbc43b08266f8489417813c52bbda82"
