version: '3.8'

services:
  calculator-app:
    build:
      context: .
      dockerfile: Dockerfile-console-app
    ports:
      - "8080:80"  
    depends_on:
      - calculator-db docker pull hazemalkhani/calculator:dev

  calculator-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "700170"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  
    volumes:
      - db-data:/var/opt/mssql/data

volumes:
  db-data:
